// Copyright (C) 2026 leeymxz
// SPDX-License-Identifier: MIT OR Apache-2.0

//! C ABI type definitions and struct layouts.
//!
//! Guidelines for ABI types:
//! - Fixed-width integer types (`u32`, `u64`) are used to ensure cross-platform layout stability.
//! - Structs generated by hydra use explicit enum types; input fields consumed from C use `u32` and are validated on read.
//! - Extensible structs include `size` and `version` fields for backwards compatibility.

#![allow(non_camel_case_types)]

use std::os::raw::c_char;

// ---------------------------------------------------------------- identities

/// Durable download job identifier (nonzero).
pub type hydra_job_id_t = u64;

/// Source (mirror) identifier, unique within an engine instance.
pub type hydra_source_id_t = u64;

/// Owned, NUL-terminated UTF-8 string allocated by hydra.
///
/// Must be freed with `hydra_string_free` and never with `free()`.
#[repr(C)]
#[derive(Debug)]
pub struct hydra_string_t {
    /// UTF-8 bytes, NUL-terminated. NULL when absent.
    pub data: *mut c_char,
    /// Length in bytes, excluding the NUL terminator.
    pub len: usize,
}

impl hydra_string_t {
    /// Returns an empty/absent string representation.
    pub const fn null() -> Self {
        Self {
            data: std::ptr::null_mut(),
            len: 0,
        }
    }
}

// -------------------------------------------------------------------- errors

/// Status and error codes returned by ABI functions.
#[repr(u32)]
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum hydra_error_code_t {
    /// Operation completed successfully.
    HYDRA_OK = 0,
    /// Invalid argument, NULL pointer, or malformed parameter.
    HYDRA_ERR_INVALID_ARGUMENT = 1,
    /// URL parsing failed or unsupported scheme.
    HYDRA_ERR_INVALID_URL = 2,
    /// Operation is invalid for the job's current state.
    HYDRA_ERR_INVALID_STATE = 3,
    /// Requested feature or scheme is unsupported.
    HYDRA_ERR_UNSUPPORTED = 4,
    /// Non-blocking call has no data available right now.
    HYDRA_ERR_AGAIN = 5,
    /// General network or transport failure.
    HYDRA_ERR_NETWORK = 6,
    /// Connection establishment failed or connection reset.
    HYDRA_ERR_CONNECTION = 7,
    /// Network or operation timeout expired.
    HYDRA_ERR_TIMEOUT = 8,
    /// Protocol error encountered.
    HYDRA_ERR_PROTOCOL = 9,
    /// Filesystem or I/O error.
    HYDRA_ERR_IO = 10,
    /// Filesystem permission denied.
    HYDRA_ERR_PERMISSION = 11,
    /// Target disk or partition has insufficient space.
    HYDRA_ERR_NO_SPACE = 12,
    /// Computed checksum does not match expected digest.
    HYDRA_ERR_CHECKSUM = 13,
    /// Integrity verification failed to read or verify target file.
    HYDRA_ERR_VERIFICATION = 14,
    /// Operation was cancelled by caller.
    HYDRA_ERR_CANCELLED = 15,
    /// Specified job, source, or file not found.
    HYDRA_ERR_NOT_FOUND = 16,
    /// Entity or job ID already exists.
    HYDRA_ERR_ALREADY_EXISTS = 17,
    /// System or configured resource limit reached.
    HYDRA_ERR_RESOURCE_LIMIT = 18,
    /// Engine is shutting down or shut down.
    HYDRA_ERR_SHUTDOWN = 19,
    /// Internal engine error or caught panic.
    HYDRA_ERR_INTERNAL = 20,
}

/// Detailed error container with OS and HTTP status metadata.
///
/// Owned strings must be released with `hydra_error_free`.
#[repr(C)]
#[derive(Debug)]
pub struct hydra_error_t {
    /// Primary error classification.
    pub code: hydra_error_code_t,
    /// Platform error code (errno / GetLastError), or 0.
    pub os_error: i32,
    /// HTTP response status code, or 0.
    pub http_status: i32,
    /// Human-readable error message.
    pub message: hydra_string_t,
}

impl hydra_error_t {
    /// Constructs a success error struct.
    pub const fn ok() -> Self {
        Self {
            code: hydra_error_code_t::HYDRA_OK,
            os_error: 0,
            http_status: 0,
            message: hydra_string_t::null(),
        }
    }
}

// ------------------------------------------------------------ job life cycle

/// Download job lifecycle states.
#[repr(u32)]
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum hydra_job_state_t {
    /// Created and pending initial start.
    HYDRA_JOB_CREATED = 0,
    /// Queued and waiting for an execution slot.
    HYDRA_JOB_QUEUED = 1,
    /// Probing source capabilities and metadata.
    HYDRA_JOB_RESOLVING = 2,
    /// Actively transferring data.
    HYDRA_JOB_DOWNLOADING = 3,
    /// Paused; partial downloads and range maps preserved.
    HYDRA_JOB_PAUSED = 4,
    /// Transfer complete; verifying checksum.
    HYDRA_JOB_VERIFYING = 5,
    /// Download successfully completed and verified.
    HYDRA_JOB_COMPLETED = 6,
    /// Job encountered an error and stopped.
    HYDRA_JOB_FAILED = 7,
    /// Job was cancelled by request.
    HYDRA_JOB_CANCELLED = 8,
}

/// Event types emitted on state transitions and progress ticks.
#[repr(u32)]
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum hydra_event_type_t {
    /// Job was created.
    HYDRA_EVENT_JOB_CREATED = 0,
    /// Job was admitted to the wait queue.
    HYDRA_EVENT_JOB_QUEUED = 1,
    /// Job started execution.
    HYDRA_EVENT_JOB_STARTED = 2,
    /// Sources resolved (size and capabilities determined).
    HYDRA_EVENT_RESOLVED = 3,
    /// Periodic download progress sample.
    HYDRA_EVENT_PROGRESS = 4,
    /// Job was paused.
    HYDRA_EVENT_PAUSED = 5,
    /// Job was resumed from paused state.
    HYDRA_EVENT_RESUMED = 6,
    /// Transfer failed and is retrying.
    HYDRA_EVENT_RETRYING = 7,
    /// Source list or active mirrors changed.
    HYDRA_EVENT_SOURCE_CHANGED = 8,
    /// Transfer stalled due to lack of progress.
    HYDRA_EVENT_STALLED = 9,
    /// Checksum verification started.
    HYDRA_EVENT_VERIFYING = 10,
    /// Job finished successfully.
    HYDRA_EVENT_COMPLETED = 11,
    /// Job failed.
    HYDRA_EVENT_FAILED = 12,
    /// Job was cancelled.
    HYDRA_EVENT_CANCELLED = 13,
    /// Engine is shutting down.
    HYDRA_EVENT_ENGINE_SHUTDOWN = 14,
}

/// Disposition of partial download files upon cancellation.
#[repr(u32)]
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum hydra_cancel_mode_t {
    /// Keep partial files on disk.
    HYDRA_CANCEL_KEEP_PARTIAL = 0,
    /// Remove partial files from disk.
    HYDRA_CANCEL_REMOVE_PARTIAL = 1,
}

/// Job queue priority level.
#[repr(u32)]
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum hydra_priority_t {
    /// Low priority.
    HYDRA_PRIORITY_LOW = 0,
    /// Normal priority (default).
    HYDRA_PRIORITY_NORMAL = 1,
    /// High priority.
    HYDRA_PRIORITY_HIGH = 2,
}

// ----------------------------------------------------------- platform policy

/// Network interface usage policy.
#[repr(u32)]
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum hydra_network_policy_t {
    /// Allow transfers over any available network.
    HYDRA_NETWORK_ANY = 0,
    /// Allow transfers over unmetered connections only.
    HYDRA_NETWORK_UNMETERED = 1,
    /// Allow transfers over Wi-Fi connections only.
    HYDRA_NETWORK_WIFI_ONLY = 2,
}

/// Power consumption profile for the engine.
#[repr(u32)]
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum hydra_power_mode_t {
    /// Full performance mode.
    HYDRA_POWER_NORMAL = 0,
    /// Reduced concurrency and lower event frequency.
    HYDRA_POWER_BATTERY_SAVER = 1,
    /// Single-connection minimal power mode.
    HYDRA_POWER_RESTRICTED = 2,
}

/// Runtime network and execution policies applied by host platform.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct hydra_runtime_policy_t {
    /// Network policy enum value (`hydra_network_policy_t`).
    pub network_policy: u32,
    /// Power mode enum value (`hydra_power_mode_t`).
    pub power_mode: u32,
    /// Nonzero to allow cellular networks.
    pub allow_cellular: u8,
    /// Nonzero to allow metered connections.
    pub allow_metered: u8,
    /// Nonzero to pause active transfers on low battery.
    pub pause_on_low_battery: u8,
    /// Nonzero to pause active transfers when app is in background.
    pub pause_when_backgrounded: u8,
    /// Reserved for future expansion; must be zero.
    pub reserved: [u8; 4],
}

// ------------------------------------------------------------------ networks

/// Forward proxy protocol type.
#[repr(u32)]
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum hydra_proxy_type_t {
    /// Direct connection without proxy.
    HYDRA_PROXY_NONE = 0,
    /// HTTP/HTTPS forward proxy.
    HYDRA_PROXY_HTTP = 1,
    /// SOCKS4 proxy.
    HYDRA_PROXY_SOCKS4 = 2,
    /// SOCKS4a proxy with remote DNS resolution.
    HYDRA_PROXY_SOCKS4A = 3,
    /// SOCKS5 proxy.
    HYDRA_PROXY_SOCKS5 = 4,
}

/// Proxy server configuration.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct hydra_proxy_config_t {
    /// Proxy protocol (`hydra_proxy_type_t`).
    pub kind: u32,
    /// Proxy port.
    pub port: u16,
    /// Reserved; must be zero.
    pub reserved: [u8; 2],
    /// Proxy hostname or IP address.
    pub host: *const c_char,
    /// Optional username, or NULL.
    pub username: *const c_char,
    /// Optional password, or NULL.
    pub password: *const c_char,
}

/// HTTP request header key-value pair.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct hydra_header_t {
    /// Header name (excluding trailing colon).
    pub name: *const c_char,
    /// Header value.
    pub value: *const c_char,
}

// -------------------------------------------------------------- verification

/// Checksum digest algorithm.
#[repr(u32)]
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum hydra_checksum_algorithm_t {
    /// No checksum verification.
    HYDRA_CHECKSUM_NONE = 0,
    /// MD5 digest (16 bytes).
    HYDRA_CHECKSUM_MD5 = 1,
    /// SHA-1 digest (20 bytes).
    HYDRA_CHECKSUM_SHA1 = 2,
    /// SHA-256 digest (32 bytes).
    HYDRA_CHECKSUM_SHA256 = 3,
    /// SHA-512 digest (64 bytes).
    HYDRA_CHECKSUM_SHA512 = 4,
    /// BLAKE3 digest (32 bytes).
    HYDRA_CHECKSUM_BLAKE3 = 5,
}

/// Checksum verification specification.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct hydra_checksum_t {
    /// Digest algorithm (`hydra_checksum_algorithm_t`).
    pub algorithm: u32,
    /// Reserved; must be zero.
    pub reserved: u32,
    /// Pointer to raw expected digest bytes, or NULL.
    pub digest: *const u8,
    /// Expected digest byte length.
    pub digest_len: usize,
}

impl hydra_checksum_t {
    /// Returns a no-verification checksum configuration.
    pub const fn none() -> Self {
        Self {
            algorithm: hydra_checksum_algorithm_t::HYDRA_CHECKSUM_NONE as u32,
            reserved: 0,
            digest: std::ptr::null(),
            digest_len: 0,
        }
    }
}

// ------------------------------------------------------------ configurations

/// Global engine configuration.
///
/// Initialise with `hydra_engine_config_init` before setting fields.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct hydra_engine_config_t {
    /// Struct size in bytes for version compatibility.
    pub size: u32,
    /// Struct version (`HYDRA_ENGINE_CONFIG_VERSION`).
    pub version: u32,

    /// Maximum number of concurrent active jobs (default 4).
    pub max_jobs: u32,
    /// Maximum connections per job ceiling (default 8).
    pub max_connections: u32,
    /// Default retry attempts for failed transfers (default 3).
    pub max_retries: u32,
    /// Minimum interval in milliseconds between progress events (default 250).
    pub progress_interval_ms: u32,
    /// Event queue capacity (default 1024).
    pub event_queue_capacity: u32,
    /// Internal runtime worker threads (0 for auto).
    pub worker_threads: u32,

    /// Engine-wide download rate limit in bytes/sec (0 = unlimited).
    pub max_bytes_per_second: u64,

    /// Nonzero to enable dynamic connection scaling (default 1).
    pub adaptive_concurrency: u8,
    /// Nonzero to enable range work stealing (default 1).
    pub range_stealing: u8,
    /// Nonzero to disable TLS certificate verification (testing only).
    pub allow_insecure_tls: u8,
    /// Reserved; must be zero.
    pub reserved0: u8,

    /// Initial network policy (`hydra_network_policy_t`).
    pub network_policy: u32,
    /// Initial power mode (`hydra_power_mode_t`).
    pub power_mode: u32,

    /// File path for durable state storage, or NULL.
    pub state_path: *const c_char,
    /// Custom HTTP User-Agent string, or NULL for default.
    pub user_agent: *const c_char,

    /// Reserved for future fields; must be zero.
    pub reserved: [u8; 32],
}

/// Download job configuration.
///
/// Initialise with `hydra_job_config_init` before setting fields.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct hydra_job_config_t {
    /// Struct size in bytes for version compatibility.
    pub size: u32,
    /// Struct version (`HYDRA_JOB_CONFIG_VERSION`).
    pub version: u32,

    /// Array of source URLs (mirrors).
    pub urls: *const *const c_char,
    /// Number of URLs in `urls` (minimum 1).
    pub url_count: usize,

    /// Destination file path.
    pub output_path: *const c_char,

    /// Array of custom HTTP headers, or NULL.
    pub headers: *const hydra_header_t,
    /// Number of headers in `headers`.
    pub header_count: usize,

    /// Optional HTTP Basic / FTP username, or NULL.
    pub username: *const c_char,
    /// Optional HTTP Basic / FTP password, or NULL.
    pub password: *const c_char,

    /// Proxy configuration for this job, or NULL.
    pub proxy: *const hydra_proxy_config_t,

    /// Checksum verification specification.
    pub checksum: hydra_checksum_t,

    /// Max connections for this job (0 inherits engine default).
    pub max_connections: u32,
    /// Max retries for this job (0 inherits engine default).
    pub max_retries: u32,
    /// Job priority (`hydra_priority_t`).
    pub priority: u32,
    /// Reserved; must be zero.
    pub reserved0: u32,

    /// Per-job download rate limit in bytes/sec (0 = unlimited).
    pub max_bytes_per_second: u64,

    /// Nonzero to resume from existing file ranges (default 1).
    pub resume: u8,
    /// Nonzero to allow adaptive concurrency (default 1).
    pub adaptive: u8,
    /// Nonzero to start transfer immediately upon creation.
    pub auto_start: u8,
    /// Reserved; must be zero.
    pub reserved1: u8,

    /// Reserved for future fields; must be zero.
    pub reserved: [u8; 32],
}

// ------------------------------------------------------------------ progress

/// Download progress metrics and transfer statistics.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct hydra_progress_t {
    /// Total bytes downloaded to disk.
    pub bytes_downloaded: u64,
    /// Total content size in bytes (0 if unknown).
    pub total_bytes: u64,
    /// Smoothed instantaneous transfer rate in bytes/sec.
    pub bytes_per_second: u64,
    /// Average transfer rate over this session in bytes/sec.
    pub average_bytes_per_second: u64,
    /// Estimated time remaining in seconds (0 if unknown).
    pub eta_seconds: u64,
    /// Number of active network connections.
    pub active_connections: u32,
    /// Number of active mirror sources.
    pub active_sources: u32,
    /// Number of completed byte ranges.
    pub completed_ranges: u32,
    /// Total number of tracked byte ranges.
    pub total_ranges: u32,
    /// Total range retry requests issued.
    pub retry_count: u64,
    /// Ranges reclaimed from a connection that stopped delivering.
    ///
    /// Counts both causes, because to a range they are the same event: a
    /// connection graded stalled by the no-progress timeout, and a connection
    /// whose fetch returned an error (a socket the peer had closed, a truncated
    /// body, a refused request). A failure the transport retries internally on a
    /// fresh connection is NOT counted — nothing was reclaimed and the range
    /// never went back to the scheduler.
    pub stall_count: u64,
}

/// Event notification emitted by the engine event queue.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct hydra_event_t {
    /// Event type classification.
    pub kind: hydra_event_type_t,
    /// Job state at event generation time.
    pub state: hydra_job_state_t,
    /// Target job ID (0 for engine-level events).
    pub job_id: hydra_job_id_t,
    /// Progress snapshot at event generation time.
    pub progress: hydra_progress_t,
    /// Error code if this is a failure event.
    pub error: hydra_error_code_t,
    /// HTTP status code, or 0.
    pub http_status: i32,
    /// Platform error code, or 0.
    pub os_error: i32,
    /// Reserved; must be ignored.
    pub reserved: u32,
    /// Timestamp in milliseconds since Unix epoch.
    pub timestamp_ms: u64,
    /// Count of coalesced or dropped low-priority events.
    pub dropped_events: u64,
}

impl Default for hydra_event_t {
    fn default() -> Self {
        Self {
            kind: hydra_event_type_t::HYDRA_EVENT_PROGRESS,
            state: hydra_job_state_t::HYDRA_JOB_CREATED,
            job_id: 0,
            progress: hydra_progress_t::default(),
            error: hydra_error_code_t::HYDRA_OK,
            http_status: 0,
            os_error: 0,
            reserved: 0,
            timestamp_ms: 0,
            dropped_events: 0,
        }
    }
}

/// Point-in-time snapshot of job status and metadata.
///
/// Owned strings must be released with `hydra_job_snapshot_free`.
#[repr(C)]
#[derive(Debug)]
pub struct hydra_job_snapshot_t {
    /// Job identifier.
    pub id: hydra_job_id_t,
    /// Current job lifecycle state.
    pub state: hydra_job_state_t,
    /// Error code if job failed.
    pub error_code: hydra_error_code_t,
    /// Progress statistics.
    pub progress: hydra_progress_t,
    /// Resolved target URL.
    pub url: hydra_string_t,
    /// Output file destination path.
    pub output_path: hydra_string_t,
    /// Suggested or inferred file name.
    pub file_name: hydra_string_t,
    /// Failure detail message, if any.
    pub error_message: hydra_string_t,
    /// Job creation timestamp (ms since epoch).
    pub created_at_ms: u64,
    /// Last start timestamp (ms since epoch), or 0.
    pub started_at_ms: u64,
    /// Completion or termination timestamp (ms since epoch), or 0.
    pub finished_at_ms: u64,
}

/// Source mirror statistics and status.
#[repr(C)]
#[derive(Debug)]
pub struct hydra_source_info_t {
    /// Source ID.
    pub id: hydra_source_id_t,
    /// Source URL.
    pub url: hydra_string_t,
    /// Total bytes downloaded from this source.
    pub bytes_downloaded: u64,
    /// Current transfer rate in bytes/sec.
    pub bytes_per_second: u64,
    /// Measured setup latency in microseconds.
    pub latency_us: u64,
    /// Active connections assigned to this source.
    pub active_connections: u32,
    /// Errors charged to this source.
    pub error_count: u32,
    /// Nonzero if source is currently active.
    pub active: u8,
    /// Reserved; must be ignored.
    pub reserved: [u8; 7],
}

/// Owned list of source statistics. Release with `hydra_source_array_free`.
#[repr(C)]
#[derive(Debug)]
pub struct hydra_source_array_t {
    /// Array items, or NULL if empty.
    pub items: *mut hydra_source_info_t,
    /// Number of items in array.
    pub len: usize,
}

// ----------------------------------------------------------------- metalink

/// An opaque, parsed Metalink document.
///
/// Created by `hydra_metalink_parse`, `hydra_metalink_open` or
/// `hydra_metalink_fetch`, and released with `hydra_metalink_free`. Immutable
/// once created, so it may be read from several threads at once.
pub enum hydra_metalink_t {}

/// Which dialect a document was written in.
#[repr(u32)]
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum hydra_metalink_version_t {
    /// The document has no recognisable Metalink namespace.
    HYDRA_METALINK_UNKNOWN = 0,
    /// Metalink 3.0, `http://www.metalinker.org/`. Preference is 0-100, higher
    /// is better — the reader converts it, so nothing downstream sees the
    /// inverted scale.
    HYDRA_METALINK_V3 = 3,
    /// Metalink 4 / RFC 5854, `urn:ietf:params:xml:ns:metalink`. Priority is
    /// 1-999999, lower is better.
    HYDRA_METALINK_V4 = 4,
}

/// One mirror named by a document, as the ranking the engine would use.
#[repr(C)]
#[derive(Debug)]
pub struct hydra_metalink_url_t {
    /// The mirror URL.
    pub url: hydra_string_t,
    /// ISO 3166-1 alpha-2 country code, lowercased, or an absent string.
    pub location: hydra_string_t,
    /// URL scheme: `http`, `https`, `ftp`, or whatever the document named.
    pub protocol: hydra_string_t,
    /// Rank after the engine's own ordering has been applied: 1 is best.
    ///
    /// Always in the RFC 5854 direction whichever dialect the document used.
    pub priority: u32,
    /// Connection ceiling the mirror stated for itself, or 0 if it stated none.
    ///
    /// A stated value NARROWS the client's own per-host ceiling and never
    /// widens it.
    pub max_connections: u32,
    /// Nonzero if this build has a transport for the URL's scheme.
    ///
    /// A document may name `rsync://` mirrors; they are visible here and are
    /// never given to a transfer.
    pub fetchable: u8,
    /// Reserved; must be ignored.
    pub reserved: [u8; 7],
}

/// Owned list of mirrors. Release with `hydra_metalink_url_array_free`.
#[repr(C)]
#[derive(Debug)]
pub struct hydra_metalink_url_array_t {
    /// Array items, or NULL if empty.
    pub items: *mut hydra_metalink_url_t,
    /// Number of items in array.
    pub len: usize,
}

/// One file entry from a document.
#[repr(C)]
#[derive(Debug)]
pub struct hydra_metalink_file_t {
    /// The document's `name`, as a relative path.
    ///
    /// Absent when the name would escape the output directory (`../`, an
    /// absolute path, a Windows drive letter or an alternate data stream);
    /// `name_usable` is then zero and the entry cannot be downloaded.
    pub name: hydra_string_t,
    /// The strongest digest the document published, as `algorithm:hex`, or an
    /// absent string.
    pub digest: hydra_string_t,
    /// The entry's `version`, or an absent string.
    pub version: hydra_string_t,
    /// Object size in bytes, or 0 if the document stated none.
    ///
    /// A stated size is what admits a mirror to a multi-source transfer: it is
    /// evidence from the publisher rather than from the mirrors, so it replaces
    /// the `ETag` agreement independent mirror operators cannot satisfy.
    pub size: u64,
    /// Piece length in bytes, or 0 if the document published no `<pieces>`.
    pub piece_length: u64,
    /// Number of piece digests published.
    pub piece_count: usize,
    /// Mirrors listed, including ones this build cannot fetch from.
    pub mirror_count: usize,
    /// Mirrors this build has a transport for.
    pub fetchable_count: usize,
    /// The publisher's DEFAULT per-mirror connection ceiling, or 0 for none.
    ///
    /// Metalink 3.0 `<resources maxconnections>`. Read as the default each
    /// mirror inherits rather than as a cap across the whole file: mirrormanager
    /// emits `maxconnections="1"` beside a seventeen-mirror list, and the
    /// aggregate reading would make that list useless. A mirror stating its own
    /// overrides it; `hydra_metalink_url_t.max_connections` reports what
    /// actually governs each one.
    pub max_connections: u32,
    /// Nonzero when the piece list tiles the stated size exactly.
    ///
    /// Zero means the two disagree, so the pieces describe a different object
    /// and are not used — the whole-file digest is then the only check.
    pub pieces_tile: u8,
    /// Nonzero if the entry carries an OpenPGP `<signature>`.
    ///
    /// Recorded, never verified: hydra does not check it, and reporting it as
    /// verified would be worse than not reporting it at all.
    pub signed: u8,
    /// Nonzero when `name` is a usable relative path.
    pub name_usable: u8,
    /// Reserved; must be ignored.
    pub reserved: [u8; 5],
}

/// Owned list of file entries. Release with `hydra_metalink_file_array_free`.
#[repr(C)]
#[derive(Debug)]
pub struct hydra_metalink_file_array_t {
    /// Array items, or NULL if empty.
    pub items: *mut hydra_metalink_file_t,
    /// Number of items in array.
    pub len: usize,
}

/// Owned list of job IDs. Release with `hydra_job_id_array_free`.
#[repr(C)]
#[derive(Debug)]
pub struct hydra_job_id_array_t {
    /// Array items, or NULL if empty.
    pub items: *mut hydra_job_id_t,
    /// Number of items in array.
    pub len: usize,
}

/// Engine-wide operational counters and metrics.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct hydra_metrics_t {
    /// Total network bytes received.
    pub bytes_received: u64,
    /// Total bytes written to disk.
    pub bytes_written: u64,
    /// Total range requests issued.
    pub request_count: u64,
    /// Total transfer retries attempted.
    pub retry_count: u64,
    /// Total errors encountered across all jobs.
    pub error_count: u64,
    /// Total ranges reclaimed from connections that stopped delivering, over
    /// this engine's lifetime. Both causes; see `hydra_progress_t::stall_count`.
    pub stall_count: u64,
    /// Total jobs created over engine lifetime.
    pub jobs_created: u64,
    /// Total jobs successfully completed.
    pub jobs_completed: u64,
    /// Total jobs failed.
    pub jobs_failed: u64,
    /// Low-priority events dropped under queue load.
    pub events_dropped: u64,
}

/// Logging verbosity levels.
#[repr(u32)]
#[derive(Clone, Copy, PartialEq, Eq, Debug, PartialOrd, Ord)]
pub enum hydra_log_level_t {
    /// Error messages.
    HYDRA_LOG_ERROR = 0,
    /// Warning messages.
    HYDRA_LOG_WARN = 1,
    /// Informational messages.
    HYDRA_LOG_INFO = 2,
    /// Debug messages.
    HYDRA_LOG_DEBUG = 3,
    /// Trace-level messages.
    HYDRA_LOG_TRACE = 4,
}

/// Optional callback function for event notifications.
pub type hydra_event_callback =
    Option<unsafe extern "C" fn(event: *const hydra_event_t, user_data: *mut std::ffi::c_void)>;

/// Optional callback function for engine log messages.
pub type hydra_log_callback = Option<
    unsafe extern "C" fn(level: u32, message: *const c_char, user_data: *mut std::ffi::c_void),
>;

// ============================================================== ABI layout

/// Frozen layout of every ABI-visible struct.
///
/// These are the numbers a compiled binding has baked into it. A field
/// reordered, a type widened, a `reserved` array resized — any of those is an
/// ABI break that compiles cleanly, links cleanly, and then hands a C caller
/// the wrong bytes at run time. So they are asserted at compile time here, and
/// mirrored by `_Static_assert`s in `examples/ffi-c/abi_smoke.c` so that both
/// sides of the boundary have to agree.
///
/// If a change here fails the build, that is the assertion doing its job.
/// Adding a field is legal only in the reserved tail of a versioned struct,
/// leaving the total size unchanged; anything else needs an ABI version bump
/// and a new set of numbers.
///
/// Only checked on 64-bit targets: pointers and `size_t` change width, so a
/// single table cannot describe both, and every platform in the build matrix is
/// 64-bit. A 32-bit port adds its own table rather than weakening this one.
#[cfg(target_pointer_width = "64")]
mod layout {
    use super::*;
    use std::mem::{align_of, offset_of, size_of};

    macro_rules! frozen {
        ($t:ty, $size:expr, $align:expr) => {
            const _: () = assert!(
                size_of::<$t>() == $size,
                concat!(stringify!($t), " changed size: this is an ABI break")
            );
            const _: () = assert!(
                align_of::<$t>() == $align,
                concat!(stringify!($t), " changed alignment: this is an ABI break")
            );
        };
    }

    frozen!(hydra_string_t, 16, 8);
    frozen!(hydra_error_t, 32, 8);
    frozen!(hydra_header_t, 16, 8);
    frozen!(hydra_proxy_config_t, 32, 8);
    frozen!(hydra_checksum_t, 24, 8);
    frozen!(hydra_runtime_policy_t, 16, 4);
    frozen!(hydra_engine_config_t, 104, 8);
    frozen!(hydra_job_config_t, 160, 8);
    frozen!(hydra_progress_t, 72, 8);
    frozen!(hydra_event_t, 120, 8);
    frozen!(hydra_job_snapshot_t, 176, 8);
    frozen!(hydra_source_info_t, 64, 8);
    frozen!(hydra_source_array_t, 16, 8);
    frozen!(hydra_job_id_array_t, 16, 8);
    frozen!(hydra_metrics_t, 80, 8);

    // Every enum is exactly 32 bits wide wherever it appears, in C, in C++ and
    // in every generated binding. That is the promise the header makes.
    const _: () = assert!(size_of::<hydra_error_code_t>() == 4);
    const _: () = assert!(size_of::<hydra_job_state_t>() == 4);
    const _: () = assert!(size_of::<hydra_event_type_t>() == 4);
    const _: () = assert!(size_of::<hydra_cancel_mode_t>() == 4);
    const _: () = assert!(size_of::<hydra_priority_t>() == 4);
    const _: () = assert!(size_of::<hydra_network_policy_t>() == 4);
    const _: () = assert!(size_of::<hydra_power_mode_t>() == 4);
    const _: () = assert!(size_of::<hydra_proxy_type_t>() == 4);
    const _: () = assert!(size_of::<hydra_checksum_algorithm_t>() == 4);
    const _: () = assert!(size_of::<hydra_log_level_t>() == 4);

    // A sample of offsets across each struct rather than all of them: the size
    // and alignment checks above already catch a widened field, and these catch
    // the reordering they would not.
    macro_rules! at {
        ($t:ty, $f:ident, $off:expr) => {
            const _: () = assert!(
                offset_of!($t, $f) == $off,
                concat!(
                    stringify!($t),
                    ".",
                    stringify!($f),
                    " moved: this is an ABI break"
                )
            );
        };
    }

    at!(hydra_error_t, message, 16);
    at!(hydra_progress_t, total_bytes, 8);
    at!(hydra_progress_t, retry_count, 56);
    at!(hydra_event_t, progress, 16);
    at!(hydra_event_t, timestamp_ms, 104);
    at!(hydra_engine_config_t, max_bytes_per_second, 32);
    at!(hydra_engine_config_t, state_path, 56);
    at!(hydra_engine_config_t, reserved, 72);
    at!(hydra_job_config_t, checksum, 72);
    at!(hydra_job_config_t, reserved, 124);
    at!(hydra_job_snapshot_t, url, 88);
}
