[workspace]
members = ["crates/hydra-core", "crates/hydra-net", "crates/hydra-stream", "crates/hydra-ffi", "crates/hydra-cli", "crates/hydra-gui", "crates/hydra-host", "crates/hydra-updater"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/leeymxz/playdl"
homepage = "https://github.com/leeymxz/playdl"

[workspace.dependencies]
pdl-core = { path = "crates/hydra-core" }
pdl-net = {  path = "crates/hydra-net" }
pdl-stream = { path = "crates/hydra-stream" }
pdl-ffi = { path = "crates/hydra-ffi" }
pdl-updater = { path = "crates/hydra-updater" }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "io-util", "time", "fs", "sync", "signal"] }
clap = { version = "4", features = ["derive"] }
clap_complete = "4.6"
crossterm = "0.29"
sha2 = "0.11"
blake3 = "1"
reed-solomon-simd = "3"
md-5 = "0.11"
sha1 = "0.11"
aes = "0.9"
cbc = { version = "0.2", features = ["block-padding"] }
memchr = "2"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "tls12", "logging"] }
tokio-rustls = { version = "0.26", default-features = false, features = ["ring", "tls12"] }
webpki-roots = "1.0"
rustls-pki-types = "1"
criterion = { version = "0.7", default-features = false, features = ["cargo_bench_support"] }

[workspace.lints.clippy]
too_many_arguments = "allow"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = "symbols"

[profile.dist]
inherits = "release"
panic = "abort"

[profile.debugging]
inherits = "release"
strip = "none"
debug = "line-tables-only"