[package]
name = "pdl-cli"
version.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later"
repository.workspace = true
homepage.workspace = true
description = "PlayDL - Multi-source download accelerator and file retriever CLI"
publish = false

[[bin]]
name = "playdl"
path = "src/main.rs"

[[bin]]
name = "pdl"
path = "src/main.rs"

[dependencies]
pdl-core = { workspace = true }
pdl-net = { workspace = true }
pdl-stream = { workspace = true }
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
pdl-updater = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
crossterm = { workspace = true }
sha2 = { workspace = true }
md-5 = { workspace = true }
sha1 = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
clap_complete = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
blake3 = { version = "1", features = ["pure"] }

[lints]
workspace = true